// The REINSW estimated-selling-price factors, as prompts rather than tick boxes.
//
// WHY PROMPTS AND NOT BOXES.
//
// Checked against the legislation on 22 Aug 2026: not one of these factors is
// prescribed anywhere. The Act asks for something narrower and quite different —
// s72A(5), give the seller evidence the estimate is reasonable, and s74, the
// Secretary may require you to substantiate it. The duty is to produce evidence
// that stands up, not to complete a list.
//
// REINSW's own form concedes this on its first line: the agent must record what
// supports the estimate "regardless of the method they used to establish this
// figure". Forty-odd boxes are one method among several.
//
// So Adam's instinct to include them was right and his first instinct to
// pre-tick them was not (24 Aug 2026 discussion). A pre-ticked box records an
// assertion the agent never made, on the one item most likely to be challenged,
// in a document generated by our software and carrying their name. Unticked
// boxes are no better: forty-two of them is the re-tick this product exists to
// delete.
//
// As prompts they cost nothing, record nothing, and help someone facing an
// empty box — which is the actual problem.
//
// EXPECTED TO BE TEMPORARY (Adam, 24 Aug 2026: "we can remove the worth
// considering prompts when the new SOI laws come in").
//
// Stage 2 of the underquoting reforms introduces a Statement of Information —
// an approved form carrying the agent's comparable sales — which will impose
// its own structure and make a hand-rolled list of factors redundant. Delete
// this file and the panel then.
//
// DO NOT delete the reasoning card with it. The same reforms add a
// record-keeping obligation covering the METHODOLOGY used to determine and
// revise the estimate, which is precisely what that box holds: it goes from
// good practice to law at the same moment these prompts stop being useful.
// See RealComply-NSW-underquoting-reforms-late-2026.md.
//
// MATERIAL FACTS ARE DELIBERATELY ABSENT. They are the one part of the REINSW
// checklist that IS law (s52(1)(b), reg 60) and they already have their own
// card. Asking again here would be the double entry the product exists to
// remove. See the pointer rendered under the panel.

export type EspPromptGroup = {
  heading: string;
  /** Shown first and highlighted: what an agent is actually asked to produce. */
  primary?: boolean;
  prompts: string[];
};

export const ESP_PROMPT_GROUPS: EspPromptGroup[] = [
  {
    heading: "Start here",
    primary: true,
    // The two that matter under s74. Everything else is context; these are the
    // answer to "substantiate it".
    prompts: ["The comparable sales you relied on", "How this property differs from them"],
  },
  {
    heading: "The market",
    prompts: [
      "State of the economy, interest rates, seasonality",
      "Buyers currently looking",
      "Comparable properties on the market now",
      "The local market",
      "Buyer feedback",
    ],
  },
  {
    heading: "Adjusting the comparables",
    prompts: [
      "Adjustments for valuations or attributes",
      "Adjustments for market movement since those sales",
      "Replacement cost, where recent sales are thin",
    ],
  },
  {
    heading: "The property itself",
    prompts: [
      "Location and nearby amenities",
      "Architectural features",
      "Zoning",
      "Use restrictions: right of way, covenants, easements, resumption",
      "Development or future-use potential",
      "Size, condition and age",
      "Structural features",
      "Land size and slope",
      "Energy efficiency",
      "Land features and views",
      "Land shape",
      "Street number or Feng Shui",
      "Deposit sum, settlement length",
      "Anything else that moves the price",
    ],
  },
  {
    heading: "Who the buyer is",
    prompts: ["Adjoining owners", "Market niches", "Developer interest"],
  },
  {
    heading: "The vendor",
    prompts: ["Their motivations", "Their instructions", "Their timing"],
  },
  {
    heading: "Marketing",
    prompts: [
      "Advertising budget",
      "Marketing methods",
      "Publications, online and print",
      "Advertisement position",
    ],
  },
];

export const ESP_PROMPT_COUNT = ESP_PROMPT_GROUPS.reduce((n, g) => n + g.prompts.length, 0);
