import { test } from "node:test";
import assert from "node:assert/strict";
import { PDFDocument, PDFPage } from "pdf-lib";
import { buildSignatureCertificate, type Signatory } from "@/lib/pdf/sign-stamp";

// What the signature page draws, and where. pdf-lib cannot read text back out
// of a PDF, so the drawing calls are recorded as they happen.
async function drawn(signatories: Signatory[]) {
  const calls: { text: string; y: number; page: PDFPage }[] = [];
  const original = PDFPage.prototype.drawText;
  PDFPage.prototype.drawText = function (this: PDFPage, text: string, options = {}) {
    calls.push({ text, y: options.y ?? 0, page: this });
    return original.call(this, text, options);
  };
  try {
    const bytes = await buildSignatureCertificate({
      title: "Supervision Guidelines Manual — v5",
      agencyName: "Cass Property",
      signatories,
      documentFileName: "SG Manual v5.pdf",
      legalBasis: "s32, Property and Stock Agents Act 2002 (NSW)",
    });
    const pages = (await PDFDocument.load(bytes)).getPageCount();
    return { calls, pages };
  } finally {
    PDFPage.prototype.drawText = original;
  }
}

const person = (i: number): Signatory => ({
  name: `Person ${i}`,
  role: "Staff member",
  signedAt: "2026-10-10T01:00:00Z",
});

test("ten signers: every name is on a page, nothing runs off the bottom", async () => {
  const { calls, pages } = await drawn(Array.from({ length: 10 }, (_, i) => person(i + 1)));
  assert.ok(pages > 1, "expected the signatures to run onto a second page");
  for (let i = 1; i <= 10; i += 1) {
    assert.ok(calls.some((c) => c.text === `Person ${i}`), `Person ${i} is missing`);
  }
  // Content stays above the bottom margin (56pt); only the footer sits below it.
  for (const c of calls) {
    if (c.text.startsWith("Generated by RealComply")) continue;
    assert.ok(c.y >= 56, `"${c.text}" drawn at y=${c.y}, inside the bottom margin`);
  }
  // Every page carries the footer.
  const footers = calls.filter((c) => c.text.startsWith("Generated by RealComply"));
  assert.equal(footers.length, pages);
  assert.equal(new Set(footers.map((f) => f.page)).size, pages);
  // The closing ETA s9 paragraph is still there.
  assert.ok(calls.some((c) => c.text.includes("Electronic Transactions Act")));
});

test("one signer stays on one page", async () => {
  const { pages } = await drawn([person(1)]);
  assert.equal(pages, 1);
});

test("names keep the letters the font can draw", async () => {
  const { calls } = await drawn([
    { ...person(1), name: "José Müller" },
    { ...person(2), name: "Nguyễn Văn Anh" },
    { ...person(3), name: "王伟", email: "wang@example.com" },
  ]);
  const texts = calls.map((c) => c.text);
  assert.ok(texts.includes("José Müller"));
  // Outside WinAnsi: spelt without the accents rather than with holes.
  assert.ok(texts.includes("Nguyen Van Anh"));
  // Nothing drawable at all: the account's email instead of a blank line.
  assert.ok(texts.includes("wang@example.com"));
});
