import type { SupabaseClient } from "@supabase/supabase-js";

// Comparable sales, and the subject property they are compared against.
//
// THE DIVISION OF LABOUR, which every function here is shaped by:
//
//   The AI produces the comparison. The agent produces the conclusion.
//
// s72A makes the estimated selling price the agent's own opinion and s72A(5)
// makes them hold evidence of its reasonableness. So the columns split cleanly
// in two. The facts — address, price, date, beds, land — are transcription off
// a document and the model does them. The weighting and the note are judgement
// and only ever come from a person. Nothing in this file writes a weighting.
//
// See RealComply-comparable-sales-AI-notes-design.md.

export type Weighting = "relied" | "considered" | "not_comparable";

export type Comparable = {
  id: string;
  address: string;
  salePrice: number | null;
  saleDate: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  carSpaces: number | null;
  landSizeSqm: number | null;
  internalAreaSqm: number | null;
  distanceM: number | null;
  propertyType: string | null;
  source: "report" | "agent";
  weighting: Weighting | null;
  agentNote: string | null;
  position: number;
};

/** The subject property's own attributes, as confirmed by a person. */
export type SubjectAttributes = {
  bedrooms: number | null;
  bathrooms: number | null;
  carSpaces: number | null;
  landSizeSqm: number | null;
  internalAreaSqm: number | null;
  conditionNote: string | null;
  /** What extraction read, awaiting confirmation. Null once confirmed or if never read. */
  suggestions: Partial<Omit<SubjectAttributes, "suggestions" | "confirmedAt">> | null;
  confirmedAt: string | null;
};

const numeric = (v: unknown): number | null =>
  v === null || v === undefined || v === "" ? null : Number(v);

function toComparable(row: Record<string, unknown>): Comparable {
  return {
    id: String(row.id),
    address: String(row.address ?? ""),
    salePrice: numeric(row.sale_price),
    saleDate: (row.sale_date as string) ?? null,
    bedrooms: numeric(row.bedrooms),
    bathrooms: numeric(row.bathrooms),
    carSpaces: numeric(row.car_spaces),
    landSizeSqm: numeric(row.land_size_sqm),
    internalAreaSqm: numeric(row.internal_area_sqm),
    distanceM: numeric(row.distance_m),
    propertyType: (row.property_type as string) ?? null,
    source: row.source === "agent" ? "agent" : "report",
    weighting: (row.weighting as Weighting) ?? null,
    agentNote: (row.agent_note as string) ?? null,
    position: Number(row.position ?? 0),
  };
}

export async function comparablesFor(
  supabase: SupabaseClient,
  propertyId: string,
): Promise<Comparable[]> {
  const { data } = await supabase
    .from("property_comparables")
    .select("*")
    .eq("property_id", propertyId)
    .order("position", { ascending: true })
    .order("created_at", { ascending: true });

  return ((data ?? []) as Array<Record<string, unknown>>).map(toComparable);
}

export function subjectAttributesFrom(row: Record<string, unknown> | null): SubjectAttributes {
  const suggestions = (row?.attribute_suggestions ?? null) as SubjectAttributes["suggestions"];
  return {
    bedrooms: numeric(row?.bedrooms),
    bathrooms: numeric(row?.bathrooms),
    carSpaces: numeric(row?.car_spaces),
    landSizeSqm: numeric(row?.land_size_sqm),
    internalAreaSqm: numeric(row?.internal_area_sqm),
    conditionNote: (row?.condition_note as string) ?? null,
    suggestions,
    confirmedAt: (row?.attributes_confirmed_at as string) ?? null,
  };
}

/** True when we know enough about the subject to compare anything against it. */
export function hasSubjectDetail(s: SubjectAttributes): boolean {
  return (
    s.bedrooms !== null ||
    s.bathrooms !== null ||
    s.landSizeSqm !== null ||
    s.internalAreaSqm !== null
  );
}

// ─────────────────────────────────────────────────────────────────────────
// How a comparable differs from the subject
// ─────────────────────────────────────────────────────────────────────────
//
// FACTS ONLY, and computed rather than described by a model. "120m² less land"
// is arithmetic and cannot be wrong. "Broadly comparable" is an opinion, and
// an opinion generated by software and shown beside a figure the agent must
// substantiate is exactly what this product must not produce.
//
// The threshold on area exists so a 2m² difference is not announced as a
// difference. Below it the two are the same size for any purpose an agent
// cares about, and saying otherwise is noise dressed as precision.

const AREA_NOISE_SQM = 15;

export function differencesFrom(subject: SubjectAttributes, c: Comparable): string[] {
  const out: string[] = [];

  const count = (mine: number | null, theirs: number | null, singular: string, plural: string) => {
    if (mine === null || theirs === null || mine === theirs) return;
    const diff = theirs - mine;
    const n = Math.abs(diff);
    out.push(`${n} ${n === 1 ? singular : plural} ${diff > 0 ? "more" : "fewer"}`);
  };

  count(subject.bedrooms, c.bedrooms, "bedroom", "bedrooms");
  count(subject.bathrooms, c.bathrooms, "bathroom", "bathrooms");
  count(subject.carSpaces, c.carSpaces, "car space", "car spaces");

  const area = (mine: number | null, theirs: number | null, label: string) => {
    if (mine === null || theirs === null) return;
    const diff = Math.round(theirs - mine);
    if (Math.abs(diff) < AREA_NOISE_SQM) return;
    out.push(`${Math.abs(diff)}m² ${diff > 0 ? "more" : "less"} ${label}`);
  };

  area(subject.landSizeSqm, c.landSizeSqm, "land");
  area(subject.internalAreaSqm, c.internalAreaSqm, "internal area");

  return out;
}

/** "1 bedroom fewer, 120m² less land" — or "" when we cannot say. */
export function differenceLine(subject: SubjectAttributes, c: Comparable): string {
  const parts = differencesFrom(subject, c);
  if (parts.length === 0) return "";
  return parts.join(", ");
}

// ─────────────────────────────────────────────────────────────────────────
// The prompts the agent actually sees
// ─────────────────────────────────────────────────────────────────────────
//
// The "Worth considering" panel offers 34 generic REINSW factors. These are
// different: they are drawn from THIS file, so the agent is answering a
// question about their own property rather than choosing from a list that
// looks the same on every listing. Same rule as the generic panel — a prompt
// is a heading, never an answer.

export function fileSpecificPrompts(subject: SubjectAttributes, comparables: Comparable[]): string[] {
  const prompts: string[] = [];
  const usable = comparables.filter((c) => c.weighting !== "not_comparable");
  if (usable.length === 0) return prompts;

  const withPrice = usable.filter((c) => c.salePrice !== null);
  if (withPrice.length >= 2) {
    const prices = withPrice.map((c) => c.salePrice as number).sort((a, b) => a - b);
    prompts.push(
      `Where this property sits against the range ${money(prices[0])} to ${money(prices[prices.length - 1])}`,
    );
  }

  const bigger = (get: (c: Comparable) => number | null, mine: number | null) =>
    mine !== null && usable.every((c) => get(c) !== null && (get(c) as number) + AREA_NOISE_SQM < mine);
  const smaller = (get: (c: Comparable) => number | null, mine: number | null) =>
    mine !== null && usable.every((c) => get(c) !== null && (get(c) as number) - AREA_NOISE_SQM > mine);

  if (bigger((c) => c.landSizeSqm, subject.landSizeSqm)) {
    prompts.push("Why the larger land here is worth what you have put on it");
  } else if (smaller((c) => c.landSizeSqm, subject.landSizeSqm)) {
    prompts.push("How the smaller land here affected your estimate");
  }

  const dated = usable
    .map((c) => c.saleDate)
    .filter((d): d is string => Boolean(d))
    .sort();
  if (dated.length > 0 && monthsAgo(dated[0]) >= 4) {
    prompts.push("Whether the market has moved since the older sales");
  }

  if (subject.conditionNote && subject.conditionNote.trim().length > 0) {
    prompts.push("How condition and presentation compare");
  }

  return prompts;
}

function money(n: number): string {
  return `$${Math.round(n).toLocaleString("en-AU")}`;
}

function monthsAgo(iso: string): number {
  const then = new Date(iso);
  if (Number.isNaN(then.getTime())) return 0;
  return (Date.now() - then.getTime()) / (1000 * 60 * 60 * 24 * 30.4);
}

// ─────────────────────────────────────────────────────────────────────────
// Assembling the agent's own fragments
// ─────────────────────────────────────────────────────────────────────────
//
// THE LINE THIS FUNCTION SITS ON, and the reason it is this dull:
//
// Every clause it produces came from the agent — which sales they relied on,
// which they rejected, and the words they wrote about each. All this does is
// put those fragments in an order and join them with "and". The software
// supplies arrangement; the person supplies content and can edit every word of
// the result before it is saved.
//
// It must never add a fact, an adjective, or a conclusion. In particular it
// must never mention a price the agent did not write — the estimate is theirs
// under s72A and a sentence that reaches it for them is the one thing this
// whole feature is not allowed to do.

export function assembleReasoning(comparables: Comparable[]): string {
  const relied = comparables.filter((c) => c.weighting === "relied");
  const rejected = comparables.filter((c) => c.weighting === "not_comparable");
  if (relied.length === 0 && rejected.length === 0) return "";

  const lines: string[] = [];

  if (relied.length > 0) {
    lines.push(`Relied on ${list(relied.map(shortAddress))}.`);
    for (const c of relied) {
      if (c.agentNote?.trim()) lines.push(`${shortAddress(c)} — ${c.agentNote.trim()}`);
    }
  }

  if (rejected.length > 0) {
    lines.push("");
    for (const c of rejected) {
      lines.push(
        c.agentNote?.trim()
          ? `Did not treat ${shortAddress(c)} as comparable — ${c.agentNote.trim()}`
          : `Did not treat ${shortAddress(c)} as comparable.`,
      );
    }
  }

  return lines.join("\n");
}

function shortAddress(c: Comparable): string {
  // Street and number only. The suburb repeats on every row and adds nothing
  // to a sentence about properties in one street's walk of each other.
  return c.address.split(",")[0].trim() || c.address;
}

function list(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

// ─────────────────────────────────────────────────────────────────────────
// The thin-reasoning nudge
// ─────────────────────────────────────────────────────────────────────────
//
// The failure mode of making this fast is forty files carrying near-identical
// reasoning, which is WORSE evidence than a short honest paragraph: it reads
// as a template, and a template is the opposite of evidence that this agent
// formed a view about this property.
//
// A note, never a block. Same posture as the rest of the product — say what
// they are looking at and let them decide.

export const THIN_REASONING_WORDS = 12;

export function reasoningNudge(reasoning: string, comparables: Comparable[]): string | null {
  const words = reasoning.trim().split(/\s+/).filter(Boolean).length;
  if (words === 0) return null;

  if (words < THIN_REASONING_WORDS) {
    return "This is quite short. If you are ever asked to substantiate the estimate, a line on which sales you relied on and how this property differs is what will do the work.";
  }

  const weighted = comparables.filter((c) => c.weighting !== null).length;
  if (comparables.length > 0 && weighted === 0) {
    return "None of the sales below are marked yet. Marking which ones you relied on is the clearest record of how you reached the estimate.";
  }

  return null;
}
