import type { SupabaseClient } from "@supabase/supabase-js";

// Comparable sales, and the subject property they are compared against.
//
// THE DIVISION OF LABOUR, which every function here is shaped by:
//
//   The AI produces the comparison. The agent produces the conclusion.
//
// s72A makes the estimated selling price the agent's own opinion and s72A(5)
// makes them hold evidence of its reasonableness. So the columns split cleanly
// in two. The facts — address, price, date, beds, land — are transcription off
// a document and the model does them. The weighting and the note are judgement
// and only ever come from a person. Nothing in this file writes a weighting.
//
// See RealComply-comparable-sales-AI-notes-design.md.

export type Weighting = "relied" | "considered" | "not_comparable";

export type Comparable = {
  id: string;
  address: string;
  salePrice: number | null;
  saleDate: string | null;
  bedrooms: number | null;
  bathrooms: number | null;
  carSpaces: number | null;
  landSizeSqm: number | null;
  internalAreaSqm: number | null;
  distanceM: number | null;
  propertyType: string | null;
  source: "report" | "agent";
  weighting: Weighting | null;
  agentNote: string | null;
  position: number;
};

/** The subject property's own attributes, as confirmed by a person. */
export type SubjectAttributes = {
  bedrooms: number | null;
  bathrooms: number | null;
  carSpaces: number | null;
  landSizeSqm: number | null;
  internalAreaSqm: number | null;
  conditionNote: string | null;
  /** Suburb, off the listing's address. Not a column — see suburbOf(). */
  addressSuburb: string | null;
  /** What extraction read, awaiting confirmation. Null once confirmed or if never read. */
  suggestions: Partial<Omit<SubjectAttributes, "suggestions" | "confirmedAt">> | null;
  confirmedAt: string | null;
};

const numeric = (v: unknown): number | null =>
  v === null || v === undefined || v === "" ? null : Number(v);

function toComparable(row: Record<string, unknown>): Comparable {
  return {
    id: String(row.id),
    address: String(row.address ?? ""),
    salePrice: numeric(row.sale_price),
    saleDate: (row.sale_date as string) ?? null,
    bedrooms: numeric(row.bedrooms),
    bathrooms: numeric(row.bathrooms),
    carSpaces: numeric(row.car_spaces),
    landSizeSqm: numeric(row.land_size_sqm),
    internalAreaSqm: numeric(row.internal_area_sqm),
    distanceM: numeric(row.distance_m),
    propertyType: (row.property_type as string) ?? null,
    source: row.source === "agent" ? "agent" : "report",
    weighting: (row.weighting as Weighting) ?? null,
    agentNote: (row.agent_note as string) ?? null,
    position: Number(row.position ?? 0),
  };
}

export async function comparablesFor(
  supabase: SupabaseClient,
  propertyId: string,
): Promise<Comparable[]> {
  const { data } = await supabase
    .from("property_comparables")
    .select("*")
    .eq("property_id", propertyId)
    .order("position", { ascending: true })
    .order("created_at", { ascending: true });

  return ((data ?? []) as Array<Record<string, unknown>>).map(toComparable);
}

export function subjectAttributesFrom(row: Record<string, unknown> | null): SubjectAttributes {
  const suggestions = (row?.attribute_suggestions ?? null) as SubjectAttributes["suggestions"];
  return {
    bedrooms: numeric(row?.bedrooms),
    bathrooms: numeric(row?.bathrooms),
    carSpaces: numeric(row?.car_spaces),
    landSizeSqm: numeric(row?.land_size_sqm),
    internalAreaSqm: numeric(row?.internal_area_sqm),
    conditionNote: (row?.condition_note as string) ?? null,
    addressSuburb: suburbOf(String(row?.address ?? "")),
    suggestions,
    confirmedAt: (row?.attributes_confirmed_at as string) ?? null,
  };
}

/** True when we know enough about the subject to compare anything against it. */
export function hasSubjectDetail(s: SubjectAttributes): boolean {
  return (
    s.bedrooms !== null ||
    s.bathrooms !== null ||
    s.landSizeSqm !== null ||
    s.internalAreaSqm !== null
  );
}

// ─────────────────────────────────────────────────────────────────────────
// How a comparable differs from the subject
// ─────────────────────────────────────────────────────────────────────────
//
// FACTS ONLY, and computed rather than described by a model. "120m² less land"
// is arithmetic and cannot be wrong. "Broadly comparable" is an opinion, and
// an opinion generated by software and shown beside a figure the agent must
// substantiate is exactly what this product must not produce.
//
// The threshold on area exists so a 2m² difference is not announced as a
// difference. Below it the two are the same size for any purpose an agent
// cares about, and saying otherwise is noise dressed as precision.

const AREA_NOISE_SQM = 15;

export function differencesFrom(subject: SubjectAttributes, c: Comparable): string[] {
  const out: string[] = [];

  const count = (mine: number | null, theirs: number | null, singular: string, plural: string) => {
    if (mine === null || theirs === null || mine === theirs) return;
    const diff = theirs - mine;
    const n = Math.abs(diff);
    out.push(`${n} ${n === 1 ? singular : plural} ${diff > 0 ? "more" : "fewer"}`);
  };

  count(subject.bedrooms, c.bedrooms, "bedroom", "bedrooms");
  count(subject.bathrooms, c.bathrooms, "bathroom", "bathrooms");
  count(subject.carSpaces, c.carSpaces, "car space", "car spaces");

  const area = (mine: number | null, theirs: number | null, label: string) => {
    if (mine === null || theirs === null) return;
    const diff = Math.round(theirs - mine);
    if (Math.abs(diff) < AREA_NOISE_SQM) return;
    out.push(`${Math.abs(diff)}m² ${diff > 0 ? "more" : "less"} ${label}`);
  };

  area(subject.landSizeSqm, c.landSizeSqm, "land");
  area(subject.internalAreaSqm, c.internalAreaSqm, "internal area");

  return out;
}

/** "1 bedroom fewer, 120m² less land" — or "" when we cannot say. */
export function differenceLine(subject: SubjectAttributes, c: Comparable): string {
  const parts = differencesFrom(subject, c);
  if (parts.length === 0) return "";
  return parts.join(", ");
}

/**
 * What this sale has IN COMMON with the listing.
 *
 * Adam, 7 Sep 2026, on the mock-up: two columns, similarities and
 * differences. The similarities turned out to be the more useful half — "4
 * bedrooms, 2 bathrooms, about the same land, same suburb" is the sentence an
 * agent writes by hand today, and it is the half that explains why a sale was
 * relied on at all.
 *
 * Same rule as the differences: arithmetic only. "Same land" is a measurement
 * within a tolerance; "comparable" would be a judgement and is not ours.
 */
export function similaritiesFrom(subject: SubjectAttributes, c: Comparable): string[] {
  const out: string[] = [];

  const count = (mine: number | null, theirs: number | null, singular: string, plural: string) => {
    if (mine === null || theirs === null || mine !== theirs) return;
    out.push(`${mine} ${mine === 1 ? singular : plural}`);
  };
  count(subject.bedrooms, c.bedrooms, "bedroom", "bedrooms");
  count(subject.bathrooms, c.bathrooms, "bathroom", "bathrooms");
  count(subject.carSpaces, c.carSpaces, "car space", "car spaces");

  const area = (mine: number | null, theirs: number | null, label: string) => {
    if (mine === null || theirs === null) return;
    if (Math.abs(Math.round(theirs - mine)) >= AREA_NOISE_SQM) return;
    out.push(`about the same ${label}`);
  };
  area(subject.landSizeSqm, c.landSizeSqm, "land");
  area(subject.internalAreaSqm, c.internalAreaSqm, "internal area");

  if (sameSuburb(subject, c)) out.push("same suburb");

  return out;
}

/**
 * Suburb match, off the address text.
 *
 * The subject's suburb is not stored as its own column — the address is one
 * string — so this compares the last comma-separated part of each. Crude, and
 * deliberately so: a miss shows as one fewer chip, which is a smaller harm
 * than a wrong claim that two properties are in the same suburb.
 */
function sameSuburb(subject: SubjectAttributes, c: Comparable): boolean {
  const theirs = suburbOf(c.address);
  const mine = subject.addressSuburb;
  return Boolean(mine && theirs && mine === theirs);
}

export function suburbOf(address: string): string | null {
  const parts = address.split(",").map((p) => p.trim()).filter(Boolean);
  if (parts.length < 2) return null;
  return parts[parts.length - 1].toLowerCase().replace(/\s+(nsw|qld|vic|wa|sa|tas|act|nt)\b.*$/i, "").trim() || null;
}

// ─────────────────────────────────────────────────────────────────────────
// The same arithmetic, worded to sit inside a sentence
// ─────────────────────────────────────────────────────────────────────────
//
// "also a house" is a fine chip and a terrible clause. The chips and the
// draft are built by separate functions rather than one reusing the other's
// strings, because a phrase that reads well standing alone in a coloured pill
// usually reads badly halfway through a sentence, and the draft is the half
// that ends up in a compliance record.

export function proseComparison(
  subject: SubjectAttributes,
  c: Comparable,
): { same: string[]; diff: string[] } {
  const same: string[] = [];
  const diff: string[] = [];

  const count = (mine: number | null, theirs: number | null, singular: string, plural: string) => {
    if (mine === null || theirs === null) return;
    if (mine === theirs) {
      same.push(plural);
      return;
    }
    const d = theirs - mine;
    const n = Math.abs(d);
    diff.push(`${n} ${n === 1 ? singular : plural} ${d > 0 ? "more" : "fewer"}`);
  };
  count(subject.bedrooms, c.bedrooms, "bedroom", "bedrooms");
  count(subject.bathrooms, c.bathrooms, "bathroom", "bathrooms");
  count(subject.carSpaces, c.carSpaces, "car space", "car spaces");

  const area = (mine: number | null, theirs: number | null, label: string) => {
    if (mine === null || theirs === null) return;
    const d = Math.round(theirs - mine);
    if (Math.abs(d) < AREA_NOISE_SQM) {
      same.push(label);
      return;
    }
    diff.push(`${Math.abs(d)}m² ${d > 0 ? "more" : "less"} ${label}`);
  };
  area(subject.landSizeSqm, c.landSizeSqm, "land");
  area(subject.internalAreaSqm, c.internalAreaSqm, "internal area");

  if (!sameSuburb(subject, c) && suburbOf(c.address)) diff.push("a different suburb");

  return { same, diff };
}

// ─────────────────────────────────────────────────────────────────────────
// The prompts the agent actually sees
// ─────────────────────────────────────────────────────────────────────────
//
// The "Worth considering" panel offers 34 generic REINSW factors. These are
// different: they are drawn from THIS file, so the agent is answering a
// question about their own property rather than choosing from a list that
// looks the same on every listing. Same rule as the generic panel — a prompt
// is a heading, never an answer.

export function fileSpecificPrompts(subject: SubjectAttributes, comparables: Comparable[]): string[] {
  const prompts: string[] = [];
  const usable = comparables.filter((c) => c.weighting !== "not_comparable");
  if (usable.length === 0) return prompts;

  const withPrice = usable.filter((c) => c.salePrice !== null);
  if (withPrice.length >= 2) {
    const prices = withPrice.map((c) => c.salePrice as number).sort((a, b) => a - b);
    prompts.push(
      `Where this property sits against the range ${money(prices[0])} to ${money(prices[prices.length - 1])}`,
    );
  }

  const bigger = (get: (c: Comparable) => number | null, mine: number | null) =>
    mine !== null && usable.every((c) => get(c) !== null && (get(c) as number) + AREA_NOISE_SQM < mine);
  const smaller = (get: (c: Comparable) => number | null, mine: number | null) =>
    mine !== null && usable.every((c) => get(c) !== null && (get(c) as number) - AREA_NOISE_SQM > mine);

  if (bigger((c) => c.landSizeSqm, subject.landSizeSqm)) {
    prompts.push("Why the larger land here is worth what you have put on it");
  } else if (smaller((c) => c.landSizeSqm, subject.landSizeSqm)) {
    prompts.push("How the smaller land here affected your estimate");
  }

  const dated = usable
    .map((c) => c.saleDate)
    .filter((d): d is string => Boolean(d))
    .sort();
  if (dated.length > 0 && monthsAgo(dated[0]) >= 4) {
    prompts.push("Whether the market has moved since the older sales");
  }

  if (subject.conditionNote && subject.conditionNote.trim().length > 0) {
    prompts.push("How condition and presentation compare");
  }

  return prompts;
}

function money(n: number): string {
  return `$${Math.round(n).toLocaleString("en-AU")}`;
}

function monthsAgo(iso: string): number {
  const then = new Date(iso);
  if (Number.isNaN(then.getTime())) return 0;
  return (Date.now() - then.getTime()) / (1000 * 60 * 60 * 24 * 30.4);
}

// ─────────────────────────────────────────────────────────────────────────
// The draft
// ─────────────────────────────────────────────────────────────────────────
//
// Adam chose this shape on 7 Sep 2026 from two mocked-up options: a factual
// paragraph the agent can accept as written, rather than one that stops
// mid-sentence to force them to finish it. His reasoning: "the agent can still
// add that they want."
//
// THE LINE IT SITS ON, and the reason it is this dull. Every clause is one of
// three things:
//
//   1. a figure printed in the comparable-sales report,
//   2. arithmetic between that report and the listing's own attributes, or
//   3. something the agent pressed or typed.
//
// It adds no fact, no adjective of quality and no conclusion. The only price
// it states other than the sale prices is the ESP the agent already recorded
// in the agency agreement — quoting their own figure back is not the software
// forming a view. It never says the estimate is reasonable. That sentence is
// the agent's to write, and the card says so.
//
// checkComparables asserts the ABSENCE of those things, because a change that
// made this function "helpful" would read as an improvement in review.

export type EspFigures = { low: number | null; high: number | null };

export function buildReasoningDraft(
  subject: SubjectAttributes,
  comparables: Comparable[],
  esp: EspFigures,
): string {
  const relied = comparables.filter((c) => c.weighting === "relied");
  const considered = comparables.filter((c) => c.weighting === "considered");
  const rejected = comparables.filter((c) => c.weighting === "not_comparable");
  if (relied.length === 0 && considered.length === 0 && rejected.length === 0) return "";

  const lines: string[] = [];

  if (esp.low !== null && esp.high !== null) {
    lines.push(
      esp.low === esp.high
        ? `Estimated selling price recorded in the agency agreement: ${money(esp.low)}.`
        : `Estimated selling price recorded in the agency agreement: ${money(esp.low)} to ${money(esp.high)}.`,
    );
    lines.push("");
  }

  if (relied.length > 0) {
    const prices = relied
      .map((c) => c.salePrice)
      .filter((p): p is number => p !== null)
      .sort((a, b) => a - b);

    let opening = `Relied on ${list(relied.map(shortAddress))}`;
    if (prices.length > 1) {
      opening += `, which sold between ${money(prices[0])} and ${money(prices[prices.length - 1])}`;
    } else if (prices.length === 1) {
      opening += `, which sold for ${money(prices[0])}`;
    }
    lines.push(`${opening}.`);

    for (const c of relied) {
      const { same, diff } = proseComparison(subject, c);
      const parts: string[] = [];
      if (same.length > 0) parts.push(`same ${list(same)}`);
      if (diff.length > 0) parts.push(list(diff));
      const note = sentence(c.agentNote);
      lines.push(
        `${shortAddress(c)} — ${parts.join("; ") || "nothing recorded to compare"}.` +
          (note ? ` ${note}` : ""),
      );
    }
  }

  if (considered.length > 0) {
    lines.push("");
    lines.push(
      `Also looked at ${list(considered.map(shortAddress))} without treating ` +
        `${considered.length > 1 ? "them" : "it"} as decisive.`,
    );
    for (const c of considered) {
      const note = sentence(c.agentNote);
      if (note) lines.push(`${shortAddress(c)} — ${note}`);
    }
  }

  if (rejected.length > 0) {
    lines.push("");
    for (const c of rejected) {
      const note = c.agentNote?.trim();
      lines.push(
        note
          ? `Did not treat ${shortAddress(c)} as comparable — ${note}.`
          : `Did not treat ${shortAddress(c)} as comparable.`,
      );
    }
  }

  return lines.join("\n");
}

/** Capitalised and closed, so the agent's fragment reads as a sentence. */
function sentence(text: string | null): string {
  const t = (text ?? "").trim();
  if (!t) return "";
  const body = t.charAt(0).toUpperCase() + t.slice(1);
  return /[.!?]$/.test(body) ? body : `${body}.`;
}

function shortAddress(c: Comparable): string {
  // Street and number only. The suburb repeats on every row and adds nothing
  // to a sentence about properties in one street's walk of each other.
  return c.address.split(",")[0].trim() || c.address;
}

function list(items: string[]): string {
  if (items.length <= 1) return items[0] ?? "";
  return `${items.slice(0, -1).join(", ")} and ${items[items.length - 1]}`;
}

// ─────────────────────────────────────────────────────────────────────────
// The thin-reasoning nudge
// ─────────────────────────────────────────────────────────────────────────
//
// The failure mode of making this fast is forty files carrying near-identical
// reasoning, which is WORSE evidence than a short honest paragraph: it reads
// as a template, and a template is the opposite of evidence that this agent
// formed a view about this property.
//
// A note, never a block. Same posture as the rest of the product — say what
// they are looking at and let them decide.

export const THIN_REASONING_WORDS = 12;

export function reasoningNudge(reasoning: string, comparables: Comparable[]): string | null {
  const words = reasoning.trim().split(/\s+/).filter(Boolean).length;
  if (words === 0) return null;

  if (words < THIN_REASONING_WORDS) {
    return "This is quite short. If you are ever asked to substantiate the estimate, a line on which sales you relied on and how this property differs is what will do the work.";
  }

  const weighted = comparables.filter((c) => c.weighting !== null).length;
  if (comparables.length > 0 && weighted === 0) {
    return "None of the sales below are marked yet. Marking which ones you relied on is the clearest record of how you reached the estimate.";
  }

  return null;
}
